'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18449
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("JarvisExplorer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _173_3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_173_3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _191_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_191_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1DocExp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1DocExp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1feed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1feed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _218_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("218_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _553_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("553_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _719() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("719", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property addfav() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addfav", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property allwindows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("allwindows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property allwindows2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("allwindows2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jarvis Explorer.
        '''</summary>
        Friend ReadOnly Property AppName() As String
            Get
                Return ResourceManager.GetString("AppName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BackgroundOffWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundOffWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''
        '''&lt;head&gt;
        '''&lt;title&gt;This site had been blocked.&lt;/title&gt;
        '''&lt;meta name=&quot;generator&quot; content=&quot;Namo WebEditor v5.0&quot;&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body bgcolor=&quot;white&quot; text=&quot;black&quot; link=&quot;blue&quot; vlink=&quot;purple&quot; alink=&quot;red&quot;&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;font face=&quot;Tahoma&quot;&gt;&lt;b&gt;This site has been blocked.&lt;/b&gt;&lt;/font&gt;&lt;/p&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;font face=&quot;Tahoma&quot;&gt;&amp;nbsp;&lt;/font&gt;&lt;/p&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;font face=&quot;Tahoma&quot;&gt;To see this site please remove it from 
        '''your blocked list.&lt;/font&gt;&lt;/p&gt;
        '''&lt;br /&gt;&lt;br /&gt;
        '''&lt;p align=&quot;center&quot;&gt;
        '''&lt;font face=&quot;Tahoma&quot;&gt;&lt;a [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Blocked() As String
            Get
                Return ResourceManager.GetString("Blocked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bulb16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bulb16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property busy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("busy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property busy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("busy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property but_print_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("but_print_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cookie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cookie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delCookie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delCookie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Delete16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Design_Mode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Design Mode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dl_Largepng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dl_Largepng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dlimage_sm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dlimage_sm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Download_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property favDock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favDock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property feed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("feed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Globe() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Globe", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Google1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Google1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property i_print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("i_print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property it_search0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("it_search0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LargeGlobe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LargeGlobe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockOpen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockOpen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NoPopUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoPopUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property popallowed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popallowed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property popBlocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popBlocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Properties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Properties", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seqarch_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seqarch_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield_exc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield_exc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield_exc16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield_exc16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shieldQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shieldQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shieldQ16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shieldQ16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Example Browser - Start Page&lt;/title&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body bgcolor=&quot;white&quot; text=&quot;black&quot; link=&quot;blue&quot; vlink=&quot;purple&quot; alink=&quot;red&quot;&gt;
        '''&lt;p align=&quot;center&quot;&gt;&lt;font face=&quot;Tahoma&quot; size=&quot;4&quot;&gt;&lt;b&gt;Jarvis Explorer&lt;br&gt;&lt;/b&gt;&lt;/font&gt;&lt;/p&gt;
        '''
        '''&lt;br&gt;&lt;br&gt;
        '''&lt;p&gt;&lt;font face=&quot;Tahoma&quot; size=&quot;2&quot;&gt;Goal: To demonstrate working with Voice Recognition and the Browser Control&lt;/font&gt;&lt;/p&gt;
        '''
        '''&lt;H2&gt;&lt;font color=&quot;#FF9900&quot; face=&quot;Tahoma&quot;&gt;Introduction&lt;/font&gt;&lt;/H2&gt;
        '''&lt;P&gt;&lt;font face=&quot;Tahoma&quot; size=&quot;2&quot;&gt;As many people know Microsoft has included a b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StartPage() As String
            Get
                Return ResourceManager.GetString("StartPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Stop16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tab_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tab_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property white_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("white_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property white_bg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("white_bg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Windows_Pop_up_Blocked() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Pop_up_Blocked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wrench_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wrench_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
